### PR TITLE
Add support of kisstvshow.to

### PR DESCRIPTION
**Pull request by AidyTheWeird**
I'm not a programmer or anything, I just tried to add this myself. Also, I'm not familiar with GitHub so I hope I didn't make any big mistake.
Please correct me if I did anything wrong.

### CODE REVIEW

**Comment by thorio** [comment]
For not knowing how anything works I'd say you did a fine job 😄
You couldn't have known this, but you just made the change in the wrong place.

**Comment by AidyTheWeird** [comment]
Oh okay, now I understand what the src folder meant... 😅

**Comment by thorio** [comment]
Now it's already working, but most of the servers are missing from the selector.

**Comment by thorio** [comment]
Now you should be able to install the patched version from [here](https://github.com/AidyTheWeird/KGrabber/raw/master/KGrabber.user.js) and test it out.

**Comment by AidyTheWeird** [comment]
It looks like its working fine.

**Comment by thorio** [comment]
merged to master, you can update from greasyfork now.

**Pull request merged**
